### ISSUE TITLE
Dont check in jQuery

### ISSUE THREAD

**Issue by afshinator** [soori8/RIO-Calculator#3]
You have a `.gitignore` file for this project - which is good.  It contains a lot of stuff... it seems your dev environment is on a windows machine?  Anyway, jQuery is a standard library, you're not going to be modifying it and so you dont need to check it in.   Just add a line in your .gitignore so it doesnt get checked into git and therefore github.

You might want to pull in jquery from a CDN instead of having a local copy.   Its an option.  See [](https://code.jquery.com/)

**Comment by soroush-b** [comment]
Doen
